pipeline {
    agent any

    parameters {
        choice(name: 'OS', choices: ['Windows', 'Ubuntu', 'MacOS'], description: 'Select the OS type for execution')
        
        choice(name: 'COMMAND', choices: [
            '--none--',
            'create-instances',
            'manage-instances',
            'list-instances',
            'create-bucket',
            'upload-file-to-bucket',
            'list-buckets',
            'create-hosted-zone',
            'manage-record',
            'destroy-resources'
        ], description: 'Choose a command to execute')

        choice(name: 'ACTION', choices: ['--none--', 'start', 'stop', 'CREATE', 'UPDATE', 'DELETE'], description: 'Action for managing instances or DNS records')

        choice(name: 'INSTANCE_TYPE', choices: ['--none--', 't3.nano', 't4g.nano'], description: 'Instance Type (for create-instances)')
        choice(name: 'INSTANCE_OS', choices: ['--none--', 'ubuntu', 'amazon-linux'], description: 'OS Type (for create-instances)')
        choice(name: 'COUNT', choices: ['1', '2'], description: 'Number of instances to create')
        string(name: 'INSTANCE_ID', defaultValue: '', description: 'Instance ID (for manage-instances)')
        choice(name: 'BUCKET_ACCESS', choices: ['--none--', 'private', 'public'], description: 'Bucket access (for create-bucket)')
        booleanParam(name: 'CONFIRM_PUBLIC_BUCKET_CREATION', defaultValue: false, description: 'Check this box to create a public S3 bucket')
        string(name: 'BUCKET_NAME', defaultValue: '', description: 'Bucket name (for upload-file-to-bucket)')
        string(name: 'FILE_PATH', defaultValue: '', description: 'Path to file (for upload-file-to-bucket)')
        string(name: 'ZONE_NAME', defaultValue: '', description: 'DNS Zone Name (for manage-record)')
        string(name: 'RECORD_NAME', defaultValue: '', description: 'Record Name (for manage-record)')
        string(name: 'RECORD_TYPE', defaultValue: '', description: 'Record Type (for manage-record)')
        string(name: 'RECORD_VALUE', defaultValue: '', description: 'Record Value (for manage-record)')
    }

   environment {
        AWS_REGION = 'us-east-1'
        AWS_DEFAULT_REGION = 'us-east-1'
        // AWS_PROFILE = 'default'
        PYTHONUNBUFFERED = '1'
    }

    stages {
        stage('Prepare Environment') {
            steps {
                script {
                    if (params.OS == 'Windows') {
                        bat '''
                        pip install -r requirements.txt
                        '''
                    } else {
                        sh '''
                        pip3 install -r requirements.txt
                        '''
                    }
                }
            }
        }
        
        stage('Execute Command') {
            steps {
                withAWS(credentials: 'AWS creds')
                {
                    script {
                        def cli_command = "python3 cli.py ${params.COMMAND}"
    
                        if (command == "create-instances") {
                            cli_command += " ${params.INSTANCE_TYPE} ${params.INSTANCE_OS} --count ${params.COUNT}"
                        } else if (command == "manage-instances") {
                            cli_command += " ${params.ACTION} ${params.INSTANCE_ID}"
                        } else if (command == "list-instances") {
                            cli_command = cli_command
                        } else if (command == "create-bucket") {
                            if (params.CONFIRM_PUBLIC_BUCKET_CREATION) {
                                env.SKIP_CONFIRMATION = 'true'  // Bypass confirmation for public bucket
                            } else {
                                env.SKIP_CONFIRMATION = 'false'  // Ask for confirmation in interactive mode
                            }
                            cli_command += " ${params.BUCKET_ACCESS}"
                        } else if (command == "upload-file-to-bucket") {
                            cli_command += " ${params.BUCKET_NAME} ${params.FILE_PATH}"
                        } else if (command == "list-buckets") {
                            cli_command = cli_command
                        } else if (command == "create-hosted-zone") {
                            cli_command = cli_command
                        } else if (command == "manage-record") {
                            cli_command += " ${params.ZONE_NAME} ${params.RECORD_NAME} ${params.RECORD_TYPE} ${params.RECORD_VALUE} ${params.ACTION}"
                        } else if (command == "destroy-resources") {
                            cli_command = cli_command
                        }

                        if (params.OS == 'Windows') {
                            bat cli_command
                        } else {
                            sh cli_command
                        }
                    }
                }
            }
        }
    }
}
